apiVersion: kubecluster.org/v1alpha1
kind: HadoopApplication
metadata:
  name: hadoopapplication-sample
spec:
  mainApplicationFile: /opt/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.1.jar
  arguments: ["pi","20","10000000000"]
  nameNodeDirFormat: true
  executorSpec:
      image: apache/hadoop:3
      replicas: 1
      volumes:
        - name: demos
          hostPath:
            path: /root/demos
      volumeMounts:
        - name: demos
          mountPath: /root/demos
      resources:
        requests:
            cpu: 2
            memory: 4Gi
        limits:
            cpu: 2
            memory: 4Gi



