apiVersion: kubecluster.org/v1alpha1
kind: HadoopCluster
metadata:
  name: hadoopcluster-sample
spec:
  hdfs:
    nameNode:
      nodeSpec:
        image: apache/hadoop:3
        replicas: 1
      format: true
      nameDir: /tmp/hadoop
      serviceType: NodePort
    dataNode:
      nodeSpec:
        image: apache/hadoop:3
        replicas: 1
  yarn:
    resourceManager:
      nodeSpec:
        image: apache/hadoop:3
        replicas: 1
      serviceType: NodePort
    nodeManager:
      nodeSpec:
        image: apache/hadoop:3
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi



